# Generated by Django 5.1.5 on 2025-01-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="profileimg",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="exams_created",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
