# Generated by Django 5.1.6 on 2026-01-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_expires_at',
        ),
    ]
